-- 코드를 입력하세요
SELECT a.AUTHOR_ID AS AUTHOR_ID ,
        a.AUTHOR_NAME AS AUTHOR_NAME,
        b.CATEGORY AS CATEGORY,
        SUM(b.PRICE *s.SALES) AS  TOTAL_SALES
FROM BOOK AS b
INNER JOIN AUTHOR AS a
    ON b.AUTHOR_ID = a.AUTHOR_ID
INNER JOIN BOOK_SALES AS s
    ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = 2022 AND MONTH(s.SALES_DATE) = 1
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;