-- 코드를 작성해주세요
SELECT P.ITEM_ID,I.ITEM_NAME,I.RARITY
FROM ITEM_TREE AS P
    LEFT JOIN ITEM_TREE AS C
    ON P.ITEM_ID = C.PARENT_ITEM_ID
    INNER JOIN ITEM_INFO AS I
    ON I.ITEM_ID = P.ITEM_ID
WHERE C.ITEM_ID IS NULL
ORDER BY P.ITEM_ID DESC;