-- 코드를 작성해주세요
SELECT CHILD.ID, IFNULL(
    (
        SELECT COUNT(*)
    FROM ECOLI_DATA AS PARENT
    WHERE PARENT.PARENT_ID=CHILD.ID
    )
,0) AS CHILD_COUNT
FROM ECOLI_DATA AS CHILD
ORDER BY CHILD.ID ASC;