-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, p.PRICE * SUM(o.SALES_AMOUNT) as SALES
from PRODUCT as p 
inner join OFFLINE_SALE as o
on p.PRODUCT_ID=o.PRODUCT_ID
GROUP BY p.PRODUCT_ID
order by SALES desc, p.PRODUCT_CODE asc;