-- 코드를 입력하세요
-- 1. 자동차 종류 = 세단 , SUV
-- 2. 2022년 11월 1일 ~ 2022년 11월 30일 대여가능
-- 3. 대여 금액 50만원 이상 200만원 미만
-- 4. 자동차 아이디, 자동차 종류, 대여 금액
-- 5. 대여 금액 내림차순, 자동차 종류 오름차순, 자동차아이디 내림차순
SELECT T1.CAR_ID,T1.CAR_TYPE,ROUND(T1.DAILY_FEE * 30 * (100-T3.DISCOUNT_RATE)/100) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR AS T1
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2 ON T1.CAR_ID = T2.CAR_ID
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS T3 ON T1.CAR_TYPE = T3.CAR_TYPE
WHERE T1.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
    ) AND
    T1.CAR_TYPE IN ('세단','SUV') AND
    T3.DURATION_TYPE LIKE '30일%'
GROUP BY T1.CAR_ID
HAVING FEE >= 500000 AND FEE<2000000
ORDER BY FEE DESC, T1.CAR_TYPE ASC, T1.CAR_ID
;
