SELECT R.FOOD_TYPE,R.REST_ID,R.REST_NAME,R.FAVORITES
FROM REST_INFO AS R
WHERE (R.FOOD_TYPE,R.FAVORITES) IN (
    SELECT FOOD_TYPE,MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) 
ORDER BY R.FOOD_TYPE DESC;