-- 코드를 입력하세요
-- 1.보호소에 들어올 때는 중성화x
-- 2.보호소에서 나갈 때는 중성화o
-- 3.ID 순서로 조회
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE,INS.NAME
FROM ANIMAL_INS AS INS
     INNER JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE 'Intact%' AND
      (OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%' OR 
        OUTS.SEX_UPON_OUTCOME LIKE'Neutered%')
ORDER BY INS.ANIMAL_ID;