-- 코드를 입력하세요
SELECT I.REST_ID,I.REST_NAME,I.FOOD_TYPE,I.FAVORITES AS FAVORITES,
        I.ADDRESS,ROUND(SUM(R.REVIEW_SCORE)/COUNT(*),2) AS SCORE
FROM REST_INFO AS I
INNER JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY R.REST_ID
ORDER BY SCORE DESC,FAVORITES DESC;