-- 코드를 입력하세요
-- 1.년,월,성별 상품 구매한 회원수 집계
-- 2. 년,월,성별 오름차순
-- 3. 성별 없으면 제외
SELECT  YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        GENDER,
        COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO AS I
    INNER JOIN ONLINE_SALE AS S
    ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER
ORDER BY YEAR ASC,MONTH ASC,GENDER ASC;