-- 코드를 입력하세요
-- 1.2022년 가입 상품 구메 회원수와 상품구매 회원 비율 (2021년 가입 회원 상품 구매/2021년 가입 전체 회원 수) 년 월 출력
-- 2. 비율은 소수점 두번째 자리에서 반올림
-- 3. 년 기준 오름차순, 월 기준 오름ㅍ차순
SELECT YEAR(SALES_DATE) AS YEAR,
       MONTH(SALES_DATE) AS MONTH,
       COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS S
INNER JOIN USER_INFO AS I ON S.USER_ID = I.USER_ID
WHERE YEAR(I.JOINED)=2021
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE)
ORDER BY YEAR ASC,MONTH ASC;
