SELECT p.PRODUCT_ID, p.PRODUCT_NAME,(p.PRICE * SUM(o.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT AS p
INNER JOIN FOOD_ORDER AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE)=2022 AND MONTH(o.PRODUCE_DATE)=5
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,p.PRODUCT_ID ASC;