-- 코드를 입력하세요
-- 1.종류 = 트럭
-- 2. 대여 금액 내림차순, ID기준 내림차순
-- 3. 7일 이상 30일 미만 / 30일 이상 90일 미만 / 90일 이상
SELECT R.HISTORY_ID,
       ROUND((R.DAILY_FEE*R.DAY) * (100-COALESCE(R.DISCOUNT,0))/100) AS FEE
FROM (
    SELECT C.CAR_TYPE,H.HISTORY_ID,P.DISCOUNT_RATE AS DISCOUNT,C.DAILY_FEE,DATEDIFF(H.END_DATE,H.START_DATE)+1 AS DAY
    FROM CAR_RENTAL_COMPANY_CAR AS C
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE=P.CAR_TYPE
    AND (
           CASE 
           WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 90 THEN '90일 이상'
           WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
           WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상'
           ELSE 'NONE'
           END
    )=P.DURATION_TYPE
                         
) AS R
WHERE R.CAR_TYPE='트럭'
ORDER BY 2 DESC,1 DESC;
     