-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF AS f
INNER JOIN (
    SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS j
ON f.FLAVOR = j.FLAVOR
ORDER BY f.TOTAL_ORDER+j.TOTAL_ORDER DESC
LIMIT 3;