-- 코드를 작성해주세요
SELECT DISTINCT d.ID,EMAIL,FIRST_NAME,LAST_NAME
FROM SKILLCODES AS s
INNER JOIN DEVELOPERS AS d
    ON d.SKILL_CODE  = d.SKILL_CODE | s.CODE
WHERE CATEGORY LIKE 'Front End'
ORDER BY d.ID ASC;