SELECT DISTINCT D.ID,
       D.EMAIL,
       D.FIRST_NAME,
       D.LAST_NAME
FROM DEVELOPERS AS D
JOIN SKILLCODES AS S 
WHERE D.SKILL_CODE=D.SKILL_CODE | S.CODE AND S.CATEGORY LIKE 'Front End'  
ORDER BY D.ID ASC;