-- 코드를 입력하세요
SELECT USER_ID, NICKNAME,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS b
INNER JOIN USED_GOODS_USER AS u
    ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3 ASC;