-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P
    INNER JOIN REST_REVIEW AS R
    ON P.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC,REVIEW_TEXT ASC;