-- 코드를 입력하세요
SELECT MCDP_CD AS 진료과코드, COUNT(*) AS 5월예약건수
FROM APPOINTMENT
WHERE YEAR(DATE_FORMAT(APNT_YMD,'%Y-%m-%d')) = 2022 AND MONTH(DATE_FORMAT(APNT_YMD,'%Y-%m-%d')) = 5
GROUP BY MCDP_CD
ORDER BY 2 ASC,1 ASC;