-- 코드를 입력하세요
-- 1. 세단 자동차 10월 대여 기록
-- 2. 자동차 ID 중복X
-- 3. 자동차 ID 기준 내림차순 정렬
SELECT DISTINCT C.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR AS C
     INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND
      MONTH(START_DATE) = 10
ORDER BY C.CAR_ID DESC;