-- 코드를 작성해주세요
SELECT i.ID AS ID,n.FISH_NAME AS FISH_NAME,i.LENGTH AS LENGTH
FROM FISH_INFO AS i
INNER JOIN FISH_NAME_INFO AS n 
ON i.FISH_TYPE = n.FISH_TYPE
WHERE i.FISH_TYPE in (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY i.ID ASC;