-- 1. 2022년도 평가 점수 가장 높은 사원 정보
-- 2. 2022녀도 사원들의 점수,사번,성명,직책,이메일
SELECT SUM(G.SCORE) AS SCORE,
      E.EMP_NO,
      E.EMP_NAME,
      E.POSITION,
      E.EMAIL
FROM HR_EMPLOYEES AS E
     INNER JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR=2022
GROUP BY E.EMP_NO,G.YEAR
ORDER BY SCORE DESC
LIMIT 1;