-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE,E.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL
FROM HR_EMPLOYEES AS E
INNER JOIN HR_GRADE AS G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, G.YEAR
HAVING G.YEAR = '2022'
ORDER BY SUM(SCORE) DESC
LIMIT 1;