SELECT U.TITLE,
       U.BOARD_ID,
       R.REPLY_ID,
       R.WRITER_ID,
       R.CONTENTS,
       DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS U
INNER JOIN USED_GOODS_REPLY AS R 
    ON U.BOARD_ID = R.BOARD_ID
WHERE YEAR(U.CREATED_DATE) = 2022 AND
      MONTH(U.CREATED_DATE) = 10
ORDER BY DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') ASC , U.TITLE ASC;