-- 코드를 작성해주세요
SELECT d.DEPT_ID AS DEPT_ID,d.DEPT_NAME_EN AS DEPT_NAME_EN,ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS d
INNER JOIN HR_EMPLOYEES AS e ON d.DEPT_ID = e.DEPT_ID
GROUP BY d.DEPT_ID
ORDER BY 3 DESC;