-- 코드를 입력하세요
SELECT b.CATEGORY,SUM(s.SALES) AS TOTAL_SALES
FROM BOOK AS b
INNER JOIN (
    SELECT BOOK_ID,SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
) AS s
ON b.BOOK_ID = s.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;